
name: LS5 NBAR

match:
  dataset:
    ga_level: P54
    product_type: NBAR
    platform:
      code: LANDSAT_5
    instrument:
      name: TM

storage:
    - name: 30m_bands
      bands:
        '10':
            dtype: int16
            fill_value: -999
            resampling_method: cubic
            varname: band_10
        '20':
            dtype: int16
            fill_value: -999
            resampling_method: cubic
            varname: band_20
        '30':
            dtype: int16
            fill_value: -999
            resampling_method: cubic
            varname: band_30
        '40':
            dtype: int16
            fill_value: -999
            resampling_method: cubic
            varname: band_40
        '50':
            dtype: int16
            fill_value: -999
            resampling_method: cubic
            varname: band_50
        '70':
            dtype: int16
            fill_value: -999
            resampling_method: cubic
            varname: band_70
    - name: 15m_band
      bands:
        '8':
            dtype: int16
            fill_value: -999
            resampling_method: linear
